---
# tasks file for tendrl-server

- debug:
    msg:
      - "Using {{ etcd_fqdn }} as etcd fqdn in tendrl config files."
      - "Using {{ etcd_ip_address }} as etcd ip address in etcd config file."
      - "Using {{ graphite_fqdn }} as graphite fqdn in tendrl config files."

- name: Make sure that libselinux-python is installed
  yum:
    name: libselinux-python
    state: latest

- name: Switch SELinux targeted policy to expected mode
  selinux:
    policy: targeted
    state: "{{ selinux_mode }}"

- name: Install tendrl-selinux
  yum:
    name=tendrl-selinux
    state=latest

- include: etcd.yml
- include: tendrl-node-agent.yml
- include: tendrl-api.yml
- include: tendrl-ui.yml
- include: tendrl-monitoring-integration.yml
- include: tendrl-notifier.yml

- name: Enable httpd service
  service:
    name=httpd
    enabled=yes

- name: Start httpd service
  service:
    name=httpd
    state=started

 - name: Reload rsyslog service
  service:
    name=rsyslog
    state=reloaded
